language: node_js

node_js:
  - "8.11.3"
  - "node"
  
cache: yarn

install:
  - travis_retry yarn install
  - yarn global add codecov

script:
  - yarn run lint
  # TODO: Enable testing
  # - yarn run test
  # - yarn run integration
  # - codecov
